package org.ntnu.idi.idatt2105.project.dto.user;

import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

/** Data transfer object for UserAnswer entity. */
@Data
@NoArgsConstructor
@AllArgsConstructor
public class UserAnswerDTO {

    /** The user answer id, autogenerated by the database. */
    private Long userAnswerId;

    /** The completed quiz id of the completed quiz that the user answered. */
    private Long completedQuizId;

    /** The question choice id of the question choice that the user answered. */
    private Long questionChoiceId;

    /** The string of the choice that the user answered */
    private String choice;

    /** If the answer is correct */
    private boolean isCorrect;

    /** The explanation of the question choice. */
    private String explanation;

    /** The question text of the question choice. */
    private String questionText;
}
