package org.ntnu.idi.idatt2105.project.dto;

import com.fasterxml.jackson.annotation.JsonProperty;
import lombok.*;

/**
 * Data transfer object representing a question choice in the application.
 */
@Getter
@Setter
@NoArgsConstructor
@AllArgsConstructor
@ToString
public class QuestionChoiceDTO {
  /**
   * The question choice id, autogenerated by the database.
   */
  private Long quizChoiceId;
  /**
   * The choice of the question.
   */
  private String choice;
  /**
   * The explanation of the choice.
   */
  private String explanation;

  /**
   * The correct choice of the question.
   */
  @JsonProperty("isCorrectChoice")
  private boolean isCorrectChoice;
}
