package org.ntnu.idi.idatt2105.project.entity;

import io.swagger.v3.oas.annotations.media.Schema;
import jakarta.persistence.*;
import java.util.List;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;

/** Class representing a category in the application. */
@Entity
@Getter
@Setter
@NoArgsConstructor
@Table(name = "completed_quizzes")
@Schema(description = "All completed quizzes by users.")
public class CompletedQuiz {
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Schema(description = "The completed quiz id, autogenerated by the database.")
    private int completedQuizId;

    @Column(name = "score")
    @Schema(description = "The score the user got on the quiz.")
    private int score;

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "user_id")
    @Schema(description = "The user that completed the quiz.")
    private User user;

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "quiz_id")
    @Schema(description = "The quiz that was completed.")
    private Quiz quiz;

    @OneToMany(mappedBy = "completedQuiz", cascade = CascadeType.ALL, orphanRemoval = true)
    @Schema(description = "The list of answers the user gave on the quiz.")
    private List<UserAnswer> userAnswerList;
}
