package org.ntnu.idi.idatt2105.project.entity;

import io.swagger.v3.oas.annotations.media.Schema;
import jakarta.persistence.*;
import java.util.Date;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;

/** Class representing a feedback in the application. */
@Entity
@Getter
@Setter
@NoArgsConstructor
@Table(name = "feedback")
@Schema(description = "Feedback from users.")
public class Feedback {
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Schema(description = "The feedback id, autogenerated by the database.")
    private int feedbackId;

    @Column(name = "feedback")
    @Schema(description = "The feedback from the user.")
    private String feedback;

    @Column(name = "date")
    @Temporal(TemporalType.TIMESTAMP)
    @Schema(description = "The date the feedback was given.")
    private Date date;

    @Column(name = "name")
    @Schema(description = "The name of the user giving feedback.")
    private String name;

    @Column(name = "email")
    @Schema(description = "The email of the user giving feedback.")
    private String email;
}
