package org.ntnu.idi.idatt2105.project.entity;

import io.swagger.v3.oas.annotations.media.Schema;
import jakarta.persistence.*;

import java.util.ArrayList;
import java.util.List;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;

/** Class representing a question in the application. */
@Entity
@Getter
@Setter
@NoArgsConstructor
@Table(name = "question")
@Schema(description = "A question in a quiz.")
public class Question {
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Schema(description = "The question id, autogenerated by the database.")
    private Long questionId;

    @Column(name = "question_text")
    @Schema(description = "The text of the question.")
    private String questionText;

    @Column(name = "tag")
    @Schema(description = "The tag of the question, to easier categorize similar questions.")
    private String tag;

    @Column(name = "multimedia")
    @Schema(description = "The multimedia of the question.")
    private String multimedia;

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "quiz_id")
    @Schema(description = "The quiz the question belongs to.")
    private Quiz quiz;

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "type_id")
    @Schema(description = "The type of question.")
    private QuestionType questionType;

    @OneToMany(mappedBy = "question", cascade = CascadeType.ALL, orphanRemoval = true)
    @Schema(description = "The list of choices for the question.")
    private List<QuestionChoice> questionChoiceList = new ArrayList<>();
}
