package org.ntnu.idi.idatt2105.project.dto.quiz;

import java.util.List;
import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;
import org.ntnu.idi.idatt2105.project.dto.user.UserAnswerDTO;

/** Data transfer object for CompletedQuiz entity. */
@Data
@NoArgsConstructor
@AllArgsConstructor
public class CompletedQuizDTO {
    /** The completed quiz id, autogenerated by the database. */
    private Long completedQuizId;

    /** The score of the completed quiz. */
    private int score;

    /** The user id of the user that completed the quiz. */
    private Long userId;

    /** The quiz id of the quiz that was completed. */
    private Long quizId;

    /** The list of user answers for the completed quiz. */
    private List<UserAnswerDTO> userAnswers;
}
