package org.ntnu.idi.idatt2105.project.dto.quiz;

import lombok.*;

/** Data transfer object representing a quiz in the application. */
@Getter
@Setter
@NoArgsConstructor
@AllArgsConstructor
public class CreateQuizDTO {
    /** The quiz id, autogenerated by the database. */
    private Long quizId;

    /** The name of the quiz. */
    private String quizName;

    /** The description of the quiz. */
    private String quizDescription;

    /** The multimedia of the quiz. */
    private String multimedia;

    /** The difficulty level of the quiz. */
    private String difficultyLevel;

    /** The category of the quiz. */
    private Long categoryId;

    /** The creator of the quiz. */
    private Long creatorId;
}
